version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
    command: npm run start:dev

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    ports:
      - "5173:4173"
    depends_on:
      - backend

  postgres:
    container_name: nest-postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=companies
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
