version: "3.8"

services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    command: npm run start:dev

  postgres:
    container_name: nest-postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
